### ISSUE TITLE
The layout should be responsive

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/NDC_OG#15]

**Comment by Bachibouzouk** [comment]
@bmlancien - what do you mean by that? less than 0.1s reaction time for example?

**Comment by nesnoj** [comment]
I think @bmlancien means that the site is displayed as intended on different systems/resolutions/.., so it adapts the content to the client. E.g. [Zurb Foundation](https://foundation.zurb.com/) is a responsive framework we're using in the StEmp apps.
[cf](https://en.wikipedia.org/wiki/Responsive_web_design)

**Comment by bmlancien** [comment]
Exactly @nesnoj , this tool should at least be presentable on tablets. On the other hand, I think that mobile size is not the priority.

**Comment by Bachibouzouk** [comment]
Closed by #34
