### ISSUE TITLE
The map color palette is not optimal

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/NDC_OG#16]
The color used for countries that have no data on electification option needs to be improved

**Comment by nesnoj** [comment]
Nice: http://colorbrewer2.org

**Comment by bmlancien** [comment]
I came up with 2 ideas:

1) If you want or have to keep the same gradient as now, I would just change the 'no data' color to white rgb(255,255,255).

![NDC_map_nodata](https://user-images.githubusercontent.com/33999424/57449073-4c58f700-725b-11e9-827c-b9f09beb3c7b.PNG)

2) A better solution would be to change the gradient--which is now from saturated color to white--to another whose lowest value still has a saturation level, instead of white. In that case we could use a light grey to represent countires that have no data. In the example I used the Darkmint gradient from [CARTOColors](https://carto.com/carto-colors/)

CSS -> (#d2fbd4,#a5dbc2,#7bbcb0,#559c9e,#3a7c89,#235d72,#123f5a)
#d2fbd4 or rgb(210,251,212) represents lowest value
#f0f0f0 or rgb(240,240,240) represents no data

![NDC_map_nodata1](https://user-images.githubusercontent.com/33999424/57449106-5e3a9a00-725b-11e9-8128-c19ae70ada12.PNG)

**Comment by bmlancien** [comment]
About the 'pie' colors, I cannot see anything right now that would be better than the actual colors. I would keep them for the moment. Using tiny pies on a map is a bad idea in general, and sadly, colors won't make it look better.
